### ISSUE TITLE
demonstration steps from video

### ISSUE THREAD

**Issue by cometta** [HazyResearch/eclair-agents#1]
May i know how do you convert the video into demonstration steps ? Is the script shared in the repo?

**Comment by Miking98** [comment]
Hi @cometta sorry for the delayed reply! Yes, please see this helper function here for how we convert the demonstration video into a series of screenshots: 

https://github.com/HazyResearch/eclair-agents/blob/d2135fef3932d3bfcfaad17acb104274ac28dd43/eclair/utils/helpers.py#L926
