### ISSUE TITLE
Data folder broken in README

### ISSUE THREAD

**Issue by mokolodi1** [HazyResearch/eclair-agents#13]
I'm trying to run the demo as described in the README, but it appears that the `data` folder to download in the README is broken: https://drive.google.com/drive/folders/1WL6pMfoAaar5uDEV-SWLalsAzCEPsuzJp?usp=sharing

It's not the same data as the `hospital_data` below based on working through the README.

I'd love to replicate this experiment—let me know if you're willing to fix the link either on here or privately.

**Comment by Miking98** [comment]
Apologies for the delay @mokolodi1 , and thank you for flagging this! README should now be updated with the correct link.
