### ISSUE TITLE
Assertion for ALLOWED_ENVS breaks when set to "desktop"

### ISSUE THREAD

**Issue by bbugs** [HazyResearch/eclair-agents#4]
### Description

The `Environment` class in `eclair/utils/executors.py` only accepts the following ENVS:

```
ALLOWED_ENVS: List[str] = ["selenium", "playwright", "none"]
```

However, `eclair/agent/record/record.py` sets the `env_type` to `"desktop"`, for example [here](https://github.com/HazyResearch/eclair-agents/blob/d2135fef3932d3bfcfaad17acb104274ac28dd43/eclair/agent/record/record.py#L255):

This makes the assertion at ```eclair/utils/executors.py``` break. See [here](https://github.com/HazyResearch/eclair-agents/blob/d2135fef3932d3bfcfaad17acb104274ac28dd43/eclair/utils/executors.py#L24)

**Comment by Miking98** [comment]
Thank you for flagging, have adjusted accordingly!
